service: LaunchDarkly

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

  stage: ${env:LDL_STAGE}
  region: ${env:LDL_AWS_REGION}

  environment:
      LDL_LAUNCHDARKLY_API_TOKEN: ${env:LDL_LAUNCHDARKLY_API_TOKEN}
      LDL_LAUNCHDARKLY_PROJECT: ${env:LDL_LAUNCHDARKLY_PROJECT}
      LDL_LAUNCHDARKLY_ENV: ${env:LDL_LAUNCHDARKLY_ENV}
      LDL_LAUNCHDARKLY_FLAGKEY: ${env:LDL_LAUNCHDARKLY_FLAGKEY}
      LDL_EC2_INSTANCE_ID: ${env:LDL_EC2_INSTANCE_ID}

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  setFlagState:
    handler: dist/src/setFlagState/handler.handle
    package:
      include:
        - dist/src/setFlagState/**

    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - pending
                - running
                - shutting-down
                - terminated
                - stopping
                - stopped

custom:
  dotenv:
    path: .env